### ISSUE TITLE
Incorrect links was opened

### ISSUE THREAD

**Issue by Kristinita** [rscherf/GitLink#10]
### Summary

Was opened incorrect links.
### Expected behavior

**Right link:**

https://github.com/Kristinita/Kristinita.GitHub.io/blob/master/Sasha-Black.html#L14
### Actual behavior

**Actual link:**

https://github.com/Kristinita/Kristinitahub.io/blob/master/Sasha-Black.html#L14
### Steps to reproduce

I tested on a version of Sublime Text without plugins and user settings.

I installed GitLink → restart Sublime Text → I open context menu in file of my repository on line 14 → `GitLink` → `Open Git URL To Line` → was opened incorrect link.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by rscherf** [comment]
Based on the links you posted here, it looks like you may have changed your repository name on Github, but that changed was never updated locally:

`Kristinita.GitHub.io` => `Kristinitahub.io`

One thing to try would be to delete your project and re-checkout the same project with the updated name.

**Comment by rscherf** [comment]
I was not suggesting that you delete your project from Github, I was suggesting that you delete your project locally and then check it out again (ensuring all of your existing changes are pushed to a branch).

**Comment by Kristinita** [comment]
@rscherf, problem reproduced for me in Windows 64-bit EN LTSB. In similar packages [**Githubinator**](https://packagecontrol.io/packages/GitHubinator) and [**Sublime GitHub**](https://packagecontrol.io/packages/sublime-github) I can get no this error.

May you tell me step-by-step, what I need to make? I'm not understand you :crying_cat_face:.

Thanks.
