### ISSUE TITLE
Support for Meta-Shift-P menu

### ISSUE THREAD

**Issue by michaelblyons** [rscherf/GitLink#11]
I would like to be able to find and use the commands from the <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> menu (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> in Windows).

**Comment by KyleKing** [comment]
@rscherf, would you be open to a PR for this?

There doesn't appear to be an option yet and I would find this feature really useful

**Comment by rscherf** [comment]
Of course! Feel free to submit one.
