### ISSUE TITLE
Can't open files in branches with slash characters in Bitbucket

### ISSUE THREAD

**Issue by rodstrom** [rscherf/GitLink#16]
I tried opening a file in a branch that has a slash character in it (feature/Name) but Bitbucket doens't seem to support this. For branches with slash characters they instead use a link looking something like this "https://bitbucket.org/foo/repobar/src/3bb054083701e4f432c5751408e2ca4d82e92732/ReadMe.md?at=feature%2Fname". If someone could look into this it would be appreciated.
Best Regards

**Comment by rscherf** [comment]
Feel free to open a pull request with the fix.
