### ISSUE TITLE
Support for opening upstream repo insted

### ISSUE THREAD

**Issue by guilhermeleobas** [rscherf/GitLink#18]
Hi @rscherf, 

It would be possible to open the upstream link instead of the base repo? For instance, when I am working in a fork, I would prefer to share the GitHub of the original repo instead of the forked one. 

I can work on something if you give me some tips on what to look for in the source code.

**Comment by ushuz** [comment]
GitLink determines remote repo by looking up `origin` remote, code here:

https://github.com/rscherf/GitLink/blob/f0de892702ea167d377e150df3cda03f3f725a36/GitLink.py#L52

So here's a simple workaround without changing code: set `origin` remote to upstream in your local git repo

**Comment by michaelblyons** [comment]
Is there a cute `@{u}` trick one could pull?
