### ISSUE TITLE
Package Control Version

### ISSUE THREAD

**Issue by KyleKing** [rscherf/GitLink#25]
It looks like the version on Package Control is out of date (11 months ago, 0.5.2): https://packagecontrol.io/packages/GitLink

The [config for PackageControl is right](https://github.com/wbond/package_control_channel/blob/eed25a776ee8148f734eb2d4ee63aefebef83685/repository/g.json#L799-L809), but it looks like the past two releases (0.6, 0.7) haven't been published: https://github.com/rscherf/GitLink/releases

Maybe Package Control doesn't recognize two-digit SemVer and changing to 0.7.0 or a new 0.7.1 might fix it?

**Comment by rscherf** [comment]
Just tagged a release for 0.7.1, but nothing it hasn't updated yet. Hmm

**Comment by michaelblyons** [comment]
It takes a couple hours for PC to notice the new version.

**Comment by rscherf** [comment]
Looks like it worked. Thanks for flagging @KyleKing
