### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by tedmiston** [rscherf/GitLink#9]
Hi,

Just wanted to say this is an excellent Sublime package and I use it daily.

I have a few repos on a self-hosted GitLab instance (not at gitlab.com) that I would like to use it with as well.  Currently running the extension's commands on those repos open broken links to github.com (as expected).

I wanted to inquire if you'd be interested in expanding scope to include GitLab?

I'd be happy to supply the PR.

Best,
Taylor

**Comment by rscherf** [comment]
I'd be happy to entertain any repository support you want to build!

**Comment by rscherf** [comment]
You may be in luck, as another contributor just added support via #19

**Comment by danilokleber** [comment]
I can't get this to work for a self-hosted GitLab instance. I guess GitLink is using the `codebasehq` "template" for the URLs. Is there a way to kinda force it to use GitLab's?
